'use client'

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Providers from "../components/Providers";
import NavBar from "@/components/NavBar";
import { Provider } from "react-redux";
import { store } from "./api/store";
import SearchBox from "@/components/SearchBox";
// const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "IMDb Website",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body>
          <Providers>
            <Header />
            <NavBar />
            <SearchBox/>
            {children}
          </Providers>
        </body>
      </Provider>
    </html>
  );
}








